config/routes.rb
BooksRecommendations::Application.routes.draw do
  root 'dashboard#index'

  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', :as => 'book'

  get 'users' => 'users#index'
  get 'users/:id' => 'users#show', :as => 'user'

  get "rank/:user_id" => 'rank#show', :as => 'rank'
  get "recommendations/:user_id" => 'recommendations#show', :as => 'recommendation'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :book_ratings
  has_many :books, through: :book_ratings

  def number_of_readed_books
    books.count
  end

  def number_of_similar_users
    unique_similar_user_ids.reject { |id| id == self.id }.size
  end

  def similar_users
    #logger.debug "Similar User IDs: #{similar_user_ids.inspect}"

    logger.debug "Unique Similar User IDs: #{unique_similar_user_ids.inspect}"

    @similar_users ||= User.includes(:book_ratings).where(id: unique_similar_user_ids)
  end

  def readed_book_ids
    @readed_book_ids ||= book_ratings.pluck(:book_id)
  end

  def similar_user_ids
    @similar_user_ids ||= BookRating.where(book_id: readed_book_ids).pluck(:user_id)
  end

  def unique_similar_user_ids
    similar_user_ids.uniq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per_page(20)
  end

  def show
    @user = User.includes(:books).find(params[:id])
  end
end

app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Leitor</th>
      <th>Localização</th>
      <th>Idade</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.id, user_path(user) %></td>
      <td><%= user.location %></td>
      <td><%= user.age %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @users %>

app/views/users/show.html.erb
<div class="row">
  <div class="span4">
    <p><strong>ID:</strong> <%= @user.id %></p>
    <p><strong>Idade:</strong> <%= @user.age %></p>
    <p><strong>Localização:</strong> <%= @user.location %></p>

    <p><%= link_to "Ver livros recomendados", recommendation_path(@user.id), :class => "btn btn-primary" %></p>
    <p><%= link_to "Ver leitores semelhantes", rank_path(@user.id), :class => "btn btn-primary" %></p>
  </div>

  <div class="span8">
    <h4>Livros lidos <span class="label label-primary"><%= @user.number_of_readed_books %></span></h4>
    <% unless @user.book_ratings.empty? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Título</th>
          <th>Avaliação</th>
        </tr>
      </thead>
      <tbody>
      <% @user.book_ratings.each do |r| %>
      <tr>
        <td><%= link_to r.book.title, r.book %></td>
        <td><span class="label label-info"><%= r.rating %></span></td>
      </tr>
      <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>